version: "3.7"
services:
  backend:
    container_name: backend-fmcg-smartshelf-poc
    build:
      context: ./backend
      dockerfile: ./app/Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000

  frontend:
    container_name: frontend-fmcg-smartshelf-poc
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: unless-stopped
    stdin_open: true
    ports:
      - 3000:3000
